apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 022814387496.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend2
  newName: 022814387496.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend2
  newTag: c84d8378
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
